src/reports/urls.py
from django.urls import path
from .views import (UploadTemplateView, 
                    create_report_view, 
                    ReportList, ReportDetail, 
                    csv_upload_view, 
                    render_pdf_view,
                    )

app_name = 'reports'

urlpatterns = [
    path('upload/', csv_upload_view, name='upload'),
    path('save/', create_report_view, name = 'create-report'),
    path('from_file/', UploadTemplateView.as_view(), name = 'from_file'),
    path('list/', ReportList.as_view(), name='list'),
    path('<pk>/', ReportDetail.as_view(), name='detail' ),
    path('pdf/<pk>', render_pdf_view, name='pdf'),
    

    ]

src/reports_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('admin/', admin.site.urls),
    path('', include("sales.urls")),
    path('reports/', include("reports.urls")),
    path('', include("profiles.urls")),
]

urlpatterns+= static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/sales/urls.py
from django.urls import path
from .views import (
    home_view,
    SaleDetailView,
    SaleListView
)


app_name = 'sales'

urlpatterns = [
    path('', home_view, name='home view'),
    path('sales/', SaleListView.as_view(), name= 'list' ), #this name help in url maping 
    path('sales/<pk>/', SaleDetailView.as_view(), name='detail')
]

src/reports/models.py
from django.db import models
from profiles.models import Profile
from django.urls import reverse
# Create your models here.

class Report(models.Model):
    name = models.CharField(max_length=120)
    image = models.ImageField(upload_to = 'charts', blank=True, null=True)
    remarks = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(Profile, on_delete=models.PROTECT)

    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse("reports:detail", kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.name)+"---"+str(self.created)

src/reports/forms.py
from django import forms
from django.forms import fields
from .models import Report


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['name', 'remarks']

src/reports/views.py
from re import T
from django.shortcuts import get_object_or_404, render
from profiles.models import Profile
from django.http import JsonResponse
from .utils import get_report_image, link_callback
from .models import Report
from .forms import ReportForm
from django.views.generic import ListView, DetailView, TemplateView
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from sales.models import Sale, Position, CSV
import csv
from django.utils.dateparse import parse_date
from products.models import Product
from customers.models import Customer
from profiles.models import Profile
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def create_report_view(request):
    form  = ReportForm(request.POST or None)
    if request.method == 'POST': #This should be a request.is_ajax() but its depreciated will improve this feature in future
        image = request.POST.get('image')
        img = get_report_image(image)
        author = Profile.objects.get(id=request.user.id)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.image = img
            instance.author = author
            instance.save()
            print(instance.image.url)
            return JsonResponse({ 'msg': 'send'})
    return JsonResponse({})

class UploadTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'reports/from_file.html'

@login_required
def csv_upload_view(request):
    if request.method == 'POST':
        csv_file_name = request.FILES.get('file').name
        csv_file = request.FILES.get('file')
        obj, created = CSV.objects.get_or_create(file_name = csv_file_name)
        if created:
            obj.csv_file = csv_file
            obj.save()
            with open(obj.csv_file.path, "r") as f:
                reader = csv.reader(f)
                reader.__next__()  #Skips the first row (which is just the name of the coulumns)
                for row in reader:
                    transaction_id = row[1]
                    product = row[2]
                    quantity = int(row[3])
                    customer = row[4]
                    date = parse_date(row[5])

                    try:
                        product_obj = Product.objects.get(name__iexact = product)
                    except Product.DoesNotExist:
                        product_obj = None
                    if product_obj is not None:
                        customer_obj, _ = Customer.objects.get_or_create(name = customer)
                        salesman_obj = Profile.objects.get(user = request.user)
                        position_obj = Position.objects.create(product = product_obj, quantity
                        =quantity, created = date)
                        print(position_obj)
                        sale_obj, _ = Sale.objects.get_or_create(transaction_id = transaction_id, customer = customer_obj, salesman = salesman_obj, created = date)
                        sale_obj.positions.add(position_obj) #just another method to add a manyToMany Field
                        sale_obj.save()
                return JsonResponse({"ex": False})
        else:
            return JsonResponse({"ex": True})
    return HttpResponse()

class ReportList(LoginRequiredMixin, ListView):
    model = Report
    template_name = 'reports/reportList.html'

class ReportDetail(LoginRequiredMixin, DetailView):
    model = Report
    template_name = 'reports/details.html'

@login_required
def render_pdf_view(request, pk):
    object = get_object_or_404(Report, pk=pk)
    template_path = 'reports/pdf.html'
    context = {'object': object}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    #if download
    #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    #if display 
    response['Content-Disposition'] = 'filename="report.pdf"' #JUST remove the atachment part
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response, link_callback=link_callback )
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

src/reports/templates/reports/details.html
{% extends 'base.html' %}
{% block title %}
    {{object.name}}
{% endblock title %}
{% block content %}
    <h2>{{object.name}}</h2>

    {% if object.image %}
    <img src="{{object.image.url}}">
    {% endif %}
    <h3>Remarks</h3>
    <h6>{{object.remarks}}</h6>
    <hr>
    <div><h7><b>Created by:</b> {{object.author}}</h7> 
    </div>
        <h7><b>Created at:</b> {{object.created}}</h7>   
{% endblock content %}

src/reports/templates/reports/from_file.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
    <script src="{% static 'reports/upload.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
upload files
{% endblock title%}

{% block content %}
<h5>Upload you sales file</h5>
</br>
<div id='alert-box'></div>
<form id='my-dropzone' class="dropzone dz">
    {% csrf_token %}
    <div class = 'fallback'>
            <input name = 'file' type="file" multiple>
        </div>

        </form>
{% endblock content %}

src/reports/templates/reports/pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>pdf viewer</title>
</head>
<body>
    <h1>{{object.name|title}}</h1>
    <hr>
    <img src='{{object.image.url}}'>
</br>
    <h3>Remarks</h3>
    <h6>{{object.remarks}}</h6>
    <hr>
    <div><h7><b>Created by: </b>{{object.author.user.username}}</h7></div>
    <h7><b>Created at: </b>{{object.created}}</h7>

</body>
</html>

src/reports/templates/reports/reportList.html
{% extends 'base.html' %}

{% block title %}
    Reports
{% endblock title %}

{%block content %}
    <h1>Reports</h1>
</br>



{% for obj in object_list %}

<div class="card" style="width: 18rem; margin-bottom: 10px;">
    {% if obj.image %}
    <img class="card-img-top" src="{{obj.image.url}}" alt="Card image cap">
    {% endif %}
    <div class="card-body">
      <h5 class="card-title">{{obj.name}} {{"  "}} {{obj.pk}}</h5>
      <p class="card-text">{{obj.remarks| truncatewords:2}}</p>
      <a href={{obj.get_absolute_url}} class="btn btn-primary">View report</a>
      <a href="{% url 'reports:pdf' obj.pk %}" target="_blank" class="btn btn-danger">PDF</a>
    </div>
  </div>
 {% endfor %}
 
{% endblock content %}